FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y devscripts debhelper build-essential && \
    rm -rf /var/lib/apt/lists/*

COPY . /work

WORKDIR /work 

ENTRYPOINT [ "bash", "script/build.sh" ]