#!/bin/bash

set -e

docker_compose_cmd="docker compose \
    --file /usr/share/openhexa/compose.yml \
    --env-file /etc/openhexa/env.conf \
    --project-name openhexa "

running_profiles="--profile frontend \
    --profile minio \
    --profile pipelines \
    --profile notebook "
all_profiles="${running_profiles} --profile spwaned-notebook"

case "$1" in
configure)
  [[ ! -r /etc/openhexa/env.conf ]] && (
    db_port=5432
    if [[ -x /usr/bin/pg_lsclusters ]]; then
      last_pgsql_port=$(pg_lsclusters --no-header | sed -e "s/[[:space:]]\+/,/g" | cut -d, -f3 | sort | uniq | tail -1)
      db_port=$((last_pgsql_port + 1))
    fi
    AWS_ACCESS_KEY_ID=$(openssl rand -hex 16) \
    AWS_SECRET_ACCESS_KEY=$(openssl rand -base64 42) \
    DB_PORT=$db_port \
      envsubst </etc/openhexa/.env.dist >/etc/openhexa/env.conf
  )

  # shellcheck disable=SC2086
  $docker_compose_cmd $all_profiles pull --policy always

  $docker_compose_cmd run app fixtures
  ;;

\
  *)
  echo "postinst called with unknown argument \`$1'" >&2
  exit 0
  ;;
esac

#DEBHELPER#

exit 0
