#!/bin/bash

set -e

case "$1" in
configure)
  /usr/share/openhexa/setup.sh -g env
  /usr/share/openhexa/setup.sh -g db

  /usr/share/openhexa/openhexa.sh -g update
  /usr/share/openhexa/openhexa.sh -g prepare
  ;;

\
  *)
  echo "postinst called with unknown argument \`$1'" >&2
  exit 0
  ;;
esac

#DEBHELPER#

exit 0
